(() => {
  const API_URL=(window.STORE_CONFIG&&window.STORE_CONFIG.apiUrl)||"https://script.google.com/macros/s/AKfycbwxFs75do4gJ941Agg0x6432z18qPjqkZ0ucutOCkaH-keZfDGP_xCPRhawbVXLIw8Y/exec";
  let brands=[];
  function esc(v){return String(v||'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
  function addStyles(){if(document.getElementById('brandLogoStyles'))return;const s=document.createElement('style');s.id='brandLogoStyles';s.textContent=`.brand-logo-section{margin-top:2px}.brand-logo-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(92px,1fr));gap:10px}.brand-logo-card{border:1px solid rgba(23,21,18,.09);background:#fff;border-radius:16px;padding:11px 8px;min-height:92px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;font:inherit;font-weight:800;color:#171512;cursor:pointer;box-shadow:0 8px 20px rgba(0,0,0,.04)}.brand-logo-card img{width:66px;height:40px;object-fit:contain;display:block}.brand-logo-card span{font-size:12px;text-align:center;line-height:1.25}.brand-logo-card.active{border-color:#b68b3d;box-shadow:0 0 0 2px rgba(182,139,61,.14)}@media(max-width:520px){.brand-logo-grid{grid-template-columns:repeat(4,minmax(0,1fr));gap:7px}.brand-logo-card{min-height:82px;padding:8px 4px;border-radius:14px}.brand-logo-card img{width:54px;height:34px}.brand-logo-card span{font-size:10px}}`;document.head.appendChild(s)}
  function ensureSection(){if(document.getElementById('brandLogoSection'))return document.getElementById('brandLogoSection');const products=document.getElementById('products');if(!products)return null;const sec=document.createElement('section');sec.id='brandLogoSection';sec.className='section container brand-logo-section';sec.innerHTML=`<div class="section-head"><div><span class="section-kicker">BRANDS</span><h2>تسوق حسب البراند</h2></div></div><div id="brandLogoGrid" class="brand-logo-grid"></div>`;products.parentNode.insertBefore(sec,products);return sec}
  function render(){const sec=ensureSection();if(!sec)return;const grid=document.getElementById('brandLogoGrid');if(!brands.length){sec.hidden=true;return}sec.hidden=false;grid.innerHTML=brands.map(b=>`<button type="button" class="brand-logo-card" data-brand-logo="${esc(b.name)}"><img src="${esc(b.logo)}" alt="${esc(b.name)}" loading="lazy" decoding="async" onerror="this.style.display='none'"><span>${esc(b.name)}</span></button>`).join('')}
  async function load(){try{const r=await fetch(API_URL+(API_URL.includes('?')?'&':'?')+'action=brands&_='+Date.now(),{cache:'no-store'});const j=await r.json();if(j&&j.success){brands=(j.brands||[]).filter(b=>b&&b.name&&b.logo);localStorage.setItem('alameer_brands_v1',JSON.stringify(brands));render();return}}catch(e){console.warn('Brands API:',e)}try{brands=JSON.parse(localStorage.getItem('alameer_brands_v1')||'[]')}catch(_){brands=[]}render()}
  document.addEventListener('click',e=>{const b=e.target.closest('[data-brand-logo]');if(!b)return;const name=b.dataset.brandLogo;try{if(typeof state!=='undefined'){state.brand=name;state.category='الكل';state.offersOnly=false;state.search='';if(typeof renderAll==='function')renderAll();document.querySelectorAll('[data-brand-logo]').forEach(x=>x.classList.toggle('active',x.dataset.brandLogo===name));document.getElementById('products')?.scrollIntoView({behavior:'smooth',block:'start'})}}catch(err){console.error(err)}});
  document.addEventListener('DOMContentLoaded',()=>{addStyles();ensureSection();load()});
})();